name: Generate Playground Assets

on:
  # push:
  workflow_dispatch:

jobs:
  generate-playground-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4

      - name: Clone GatherPress sourcecode.
        uses: actions/checkout@v4
        with:
          repository: 'carstingaxion/gatherpress'
          path: 'wp-content/plugins/gatherpress'
          ref: export-import--plus-block-cherries

      - name: Clone gatherpress-query-loop sourcecode.
        uses: actions/checkout@v4
        with:
          repository: 'carstingaxion/gatherpress-query-loop'
          path: 'wp-content/plugins/gatherpress-query-loop'
          ref: gpql

      - name: Clone gatherpress-venue sourcecode.
        uses: actions/checkout@v4
        with:
          repository: 'carstingaxion/gatherpress-venue'
          path: 'wp-content/plugins/gatherpress-venue'

      - name: Clone gatherpress-venue-website sourcecode.
        uses: actions/checkout@v4
        with:
          repository: 'carstingaxion/gatherpress-venue-website'
          path: 'wp-content/plugins/gatherpress-venue-website'

      - name: Copy built assets into ZIP for extraction inside Playground.
        run: |
          zip -FSr zips/playground-assets.zip wp-content -x "*.git*" "*.mp4*" "*/jetpack/"
          rm -rf wp-content

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Persist prepared assets'
